### ISSUE TITLE
Cannot load libraries due to 'utils/filter.rb' not being found

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec-habitat#40]
# Describe the problem

At some point recently, InSpec moved the location of the `utils/filter` file to be more properly under `inspec/utils/filter`.  This broke the two plural resources.

## Possible Solution

Update the require path.

**Comment by ericcalabretta** [comment]
Example Error message 

```
Traceback (most recent call last):
	27: from /usr/local/bin/inspec:343:in `<main>'
	26: from /usr/local/bin/inspec:343:in `load'
	25: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.7.3/bin/inspec:11:in `<top (required)>'
	24: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/base_cli.rb:31:in `start'
	23: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	22: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	21: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	20: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	19: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/cli.rb:297:in `exec'
	18: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/runner.rb:121:in `run'
	17: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/runner.rb:93:in `load'
	16: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/runner.rb:93:in `each'
	15: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/runner.rb:99:in `block in load'
	14: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/profile.rb:233:in `load_libraries'
	13: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/profile.rb:233:in `each_with_index'
	12: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/profile.rb:233:in `each'
	11: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/profile.rb:248:in `block in load_libraries'
	10: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/profile.rb:256:in `load_libraries'
	 9: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/profile_context.rb:134:in `load_libraries'
	 8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/profile_context.rb:134:in `each'
	 7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/profile_context.rb:136:in `block in load_libraries'
	 6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/profile_context.rb:149:in `load_library_file'
	 5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/profile_context.rb:160:in `load_with_context'
	 4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/profile_context.rb:160:in `instance_eval'
	 3: from libraries/habitat_packages.rb:1:in `load_with_context'
	 2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/dsl_shared.rb:13:in `require'
	 1: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- utils/filter (LoadError)
```
